"use client";

import { CaretLeft, CheckCircle, ClipboardText, CopySimple, Package, Plus, ShippingContainer, Storefront, Wrench, X } from "@phosphor-icons/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { allocateShipmentMachines, copyMachineAsset, createShipment, deleteMachineAsset, loadMachineAssetWorkspace, patchShipment, patchVenueMachine, type MachineAssetWorkspace } from "../../lib/machine-assets";
import type { MissingPart, ShipmentStatus, VenueMachine } from "../../types/machine";
import { ProductNavigation } from "../navigation/ProductNavigation";
import { getSupabaseClient } from "../../lib/supabase/client";

type Tab = "all" | "shipments" | "sale" | "repairs";
const emptyWorkspace: MachineAssetWorkspace = { venues: [], models: [], units: [], shipments: [], shipmentItems: [] };
const labels: Record<Tab, string> = { all: "All Machines", shipments: "Shipments", sale: "For Sale", repairs: "Repairs" };
const statuses: ShipmentStatus[] = ["ORDERED", "IN_PRODUCTION", "IN_SHIPMENT", "ARRIVED", "CLOSED"];
const errorMessage = (cause: unknown, fallback: string) => typeof cause === "object" && cause !== null && "message" in cause && typeof cause.message === "string" ? cause.message : cause instanceof Error ? cause.message : fallback;

const statusLabel = (status: string) => status.replaceAll("_", " ");
const machineName = (unit: VenueMachine, workspace: MachineAssetWorkspace) => workspace.models.find((model) => model.id === unit.machineId)?.name ?? "Unknown model";
const machineSize = (unit: VenueMachine, workspace: MachineAssetWorkspace) => {
  const model = workspace.models.find((item) => item.id === unit.machineId);
  const width = unit.useCustomDimensions ? unit.customWidthMm : model?.widthMm;
  const depth = unit.useCustomDimensions ? unit.customDepthMm : model?.depthMm;
  return width && depth ? `${width} × ${depth} mm` : "Dimensions unavailable";
};

export function MachineRegistry() {
  const [workspace, setWorkspace] = useState(emptyWorkspace); const [tab, setTab] = useState<Tab>("all");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState(""); const [venueFilter, setVenueFilter] = useState("all"); const [categoryFilter, setCategoryFilter] = useState("all");
  const [view, setView] = useState<"table" | "cards">("table"); const [selectedId, setSelectedId] = useState<string | null>(null); const [shipmentOpen, setShipmentOpen] = useState(false); const [allocateId, setAllocateId] = useState<string | null>(null);
  const refreshVersion = useRef(0);
  /** Cloud → React only. A stale network response cannot replace a newer one. */
  const refresh = useCallback(async (showLoading = true) => {
    const version = ++refreshVersion.current;
    if (showLoading) setLoading(true);
    try {
      const next = await loadMachineAssetWorkspace();
      if (version !== refreshVersion.current) return;
      setWorkspace(next);
      setError(null);
    } catch (cause) {
      if (version === refreshVersion.current) setError(errorMessage(cause, "Could not load machine assets."));
    } finally {
      if (showLoading && version === refreshVersion.current) setLoading(false);
    }
  }, []);
  useEffect(() => { void refresh(); }, []);
  /**
   * Realtime changes always re-read the cloud snapshot.  There is no local
   * cache and no write-back path here, so a remote update cannot echo or
   * revive a stale machine/shipment on this page.
   */
  useEffect(() => {
    const client = getSupabaseClient();
    if (!client) return;
    let disposed = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const scheduleRefresh = () => {
      if (timer) clearTimeout(timer);
      timer = setTimeout(() => { if (!disposed) void refresh(false); }, 150);
    };
    const channel = client.channel("machine-assets-realtime")
      .on("postgres_changes", { event: "*", schema: "public", table: "venues" }, scheduleRefresh)
      .on("postgres_changes", { event: "*", schema: "public", table: "catalog_machines" }, scheduleRefresh)
      .on("postgres_changes", { event: "*", schema: "public", table: "venue_machines" }, scheduleRefresh)
      .on("postgres_changes", { event: "*", schema: "public", table: "shipments" }, scheduleRefresh)
      .on("postgres_changes", { event: "*", schema: "public", table: "shipment_items" }, scheduleRefresh)
      .subscribe();
    return () => { disposed = true; if (timer) clearTimeout(timer); void client.removeChannel(channel); };
  }, [refresh]);
  const selected = workspace.units.find((unit) => unit.id === selectedId) ?? null;
  const categories = useMemo(() => [...new Set(workspace.models.map((item) => item.category))].sort(), [workspace.models]);
  const shipmentUnitIds = new Set(workspace.shipmentItems.map((item) => item.venueMachineId));
  const rows = useMemo(() => workspace.units.filter((unit) => {
    const model = workspace.models.find((item) => item.id === unit.machineId); const needle = `${unit.machineCode} ${model?.name ?? ""} ${model?.category ?? ""}`.toLowerCase();
    if (search && !needle.includes(search.toLowerCase())) return false;
    if (venueFilter === "unassigned" && unit.venueId !== null) return false;
    if (venueFilter !== "all" && venueFilter !== "unassigned" && unit.venueId !== venueFilter) return false;
    if (categoryFilter !== "all" && model?.category !== categoryFilter) return false;
    if (tab === "sale" && !unit.forSale) return false;
    if (tab === "repairs" && unit.maintenanceStatus === "OK") return false;
    return true;
  }), [workspace, search, venueFilter, categoryFilter, tab]);
  const updateUnit = async (id: string, patch: Parameters<typeof patchVenueMachine>[1]) => { setSaving(true); try { await patchVenueMachine(id, patch); await refresh(); } catch (cause) { setError(errorMessage(cause, "Could not update machine.")); } finally { setSaving(false); } };
  const duplicate = async (unit: VenueMachine) => {
    setSaving(true); try {
      await copyMachineAsset(unit, workspace.units); await refresh();
    } catch (cause) { setError(errorMessage(cause, "Could not copy machine.")); } finally { setSaving(false); }
  };
  const remove = async (unit: VenueMachine) => { if (!window.confirm(`Delete ${unit.machineCode}? This removes the physical machine and its placement.`)) return; setSaving(true); try { await deleteMachineAsset(unit.id); setSelectedId(null); await refresh(); } catch (cause) { setError(errorMessage(cause, "Could not delete machine.")); } finally { setSaving(false); } };

  return <main className="asset-app"><header className="app-header"><div className="brand"><div className="brand-mark">K</div><span>KOKO <b>Arcade</b></span></div><ProductNavigation /><div className="header-actions"><span className="saved-state">Cloud workspace</span></div></header>
    <section className="asset-shell"><aside className="asset-sidebar"><a href="/floor-plan" className="asset-back"><CaretLeft size={16} /> Floor Plans</a><h1>Machines</h1><p>Physical asset registry</p>{(["all", "shipments", "sale", "repairs"] as Tab[]).map((item) => <button key={item} className={tab === item ? "asset-tab asset-tab--active" : "asset-tab"} onClick={() => { setTab(item); setSelectedId(null); }}><span>{item === "all" ? <ClipboardText size={16} /> : item === "shipments" ? <ShippingContainer size={16} /> : item === "sale" ? <Storefront size={16} /> : <Wrench size={16} />}</span>{labels[item]}{item === "sale" ? <em>{workspace.units.filter((unit) => unit.forSale).length}</em> : item === "repairs" ? <em>{workspace.units.filter((unit) => unit.maintenanceStatus !== "OK").length}</em> : null}</button>)}</aside>
      <section className="asset-content"><div className="asset-heading"><div><p className="eyebrow">Operations</p><h2>{labels[tab]}</h2><span>{tab === "all" ? "One row for every physical machine." : tab === "shipments" ? "Inbound shipments own real physical machine records." : tab === "sale" ? "Units currently offered for sale." : "Machines requiring attention."}</span></div>{tab === "shipments" ? <button className="asset-primary" onClick={() => setShipmentOpen(true)}><Plus size={16} /> New shipment</button> : <div className="asset-view-toggle"><button className={view === "table" ? "active" : ""} onClick={() => setView("table")}>Table</button><button className={view === "cards" ? "active" : ""} onClick={() => setView("cards")}>Cards</button></div>}</div>
        {error ? <div className="asset-error">{error}<button onClick={() => setError(null)}><X size={14} /></button></div> : null}
        {tab === "shipments" ? <ShipmentList workspace={workspace} shipmentUnitIds={shipmentUnitIds} onRefresh={refresh} onAllocate={setAllocateId} setError={setError} /> : <><div className="asset-filters"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search code, model or type…" /><select value={venueFilter} onChange={(event) => setVenueFilter(event.target.value)}><option value="all">All locations</option><option value="unassigned">Unassigned / in shipment</option>{workspace.venues.map((venue) => <option value={venue.id} key={venue.id}>{venue.name}</option>)}</select><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="all">All types</option>{categories.map((category) => <option value={category} key={category}>{category}</option>)}</select><span>{rows.length} machines</span></div>{loading ? <div className="asset-loading">Loading shared machine assets…</div> : view === "table" ? <MachineTable rows={rows} workspace={workspace} shipmentUnitIds={shipmentUnitIds} selectedId={selectedId} onSelect={setSelectedId} /> : <MachineCards rows={rows} workspace={workspace} shipmentUnitIds={shipmentUnitIds} onSelect={setSelectedId} />}</>}
      </section>{selected ? <MachineDrawer unit={selected} workspace={workspace} shipmentUnitIds={shipmentUnitIds} saving={saving} onClose={() => setSelectedId(null)} onUpdate={updateUnit} onDuplicate={() => void duplicate(selected)} onDelete={() => void remove(selected)} /> : null}</section>
    {shipmentOpen ? <ShipmentDialog models={workspace.models} units={workspace.units} onClose={() => setShipmentOpen(false)} onSaved={async () => { setShipmentOpen(false); await refresh(); }} setError={setError} /> : null}
    {allocateId ? <AllocateDialog shipment={workspace.shipments.find((item) => item.id === allocateId)!} workspace={workspace} onClose={() => setAllocateId(null)} onSaved={async () => { setAllocateId(null); await refresh(); }} setError={setError} /> : null}
  </main>;
}

function MachineTable({ rows, workspace, shipmentUnitIds, selectedId, onSelect }: { rows: VenueMachine[]; workspace: MachineAssetWorkspace; shipmentUnitIds: Set<string>; selectedId: string | null; onSelect: (id: string) => void }) { return <div className="asset-table"><div className="asset-table-head"><span>Machine</span><span>Code</span><span>Location</span><span>Condition</span><span>Maintenance</span><span>Logistics</span></div>{rows.map((unit) => { const venue = workspace.venues.find((item) => item.id === unit.venueId); const inShipment = shipmentUnitIds.has(unit.id); return <button key={unit.id} className={selectedId === unit.id ? "asset-row asset-row--selected" : "asset-row"} onClick={() => onSelect(unit.id)}><span><strong>{machineName(unit, workspace)}</strong><small>{workspace.models.find((model) => model.id === unit.machineId)?.category ?? "Uncategorised"} · {machineSize(unit, workspace)}</small></span><b>{unit.machineCode}</b><span>{venue?.name ?? (inShipment ? "In shipment" : "Unassigned")}</span><span className={`asset-pill asset-pill--${unit.condition.toLowerCase()}`}>{unit.condition}</span><span className={unit.maintenanceStatus === "OK" ? "asset-muted" : "asset-warning"}>{statusLabel(unit.maintenanceStatus)}</span><span>{inShipment ? "IN SHIPMENT" : unit.venueId ? "AT VENUE" : "UNASSIGNED"}</span></button>; })}{!rows.length ? <div className="asset-empty">No machines match these filters.</div> : null}</div>; }
function MachineCards({ rows, workspace, shipmentUnitIds, onSelect }: { rows: VenueMachine[]; workspace: MachineAssetWorkspace; shipmentUnitIds: Set<string>; onSelect: (id: string) => void }) { return <div className="asset-cards">{rows.map((unit) => { const model = workspace.models.find((item) => item.id === unit.machineId); return <button key={unit.id} className="asset-card" onClick={() => onSelect(unit.id)}>{model?.imageUrl ? <img src={model.imageUrl} alt="" /> : <div className="asset-image-fallback">No image</div>}<span><b>{model?.name ?? "Unknown model"}</b><small>{unit.machineCode} · {workspace.venues.find((venue) => venue.id === unit.venueId)?.name ?? (shipmentUnitIds.has(unit.id) ? "In shipment" : "Unassigned")}</small><em>{unit.forSale ? "For sale" : unit.maintenanceStatus !== "OK" ? statusLabel(unit.maintenanceStatus) : "Available"}</em></span></button>; })}</div>; }
function MachineDrawer({ unit, workspace, shipmentUnitIds, saving, onClose, onUpdate, onDuplicate, onDelete }: { unit: VenueMachine; workspace: MachineAssetWorkspace; shipmentUnitIds: Set<string>; saving: boolean; onClose: () => void; onUpdate: (id: string, patch: Parameters<typeof patchVenueMachine>[1]) => Promise<void>; onDuplicate: () => void; onDelete: () => void }) { const [note, setNote] = useState(unit.maintenanceNote ?? ""); const [part, setPart] = useState(""); const model = workspace.models.find((item) => item.id === unit.machineId); const venue = workspace.venues.find((item) => item.id === unit.venueId); const saveNote = () => void onUpdate(unit.id, { maintenanceNote: note }); const addPart = () => { const clean = part.trim(); if (!clean) return; void onUpdate(unit.id, { missingParts: [...unit.missingParts, { id: `part_${Date.now()}`, name: clean, quantity: 1 }] }).then(() => setPart("")); };
  return <aside className="asset-drawer"><button className="asset-close" onClick={onClose}><X size={18} /></button><p className="eyebrow">Physical asset</p><h2>{model?.name ?? "Unknown model"}</h2><b className="asset-code">{unit.machineCode}</b>{model?.imageUrl ? <img className="asset-drawer-image" src={model.imageUrl} alt="" /> : null}<dl><div><dt>Location</dt><dd>{venue?.name ?? (shipmentUnitIds.has(unit.id) ? "In shipment" : "Unassigned")}</dd></div><div><dt>Size</dt><dd>{machineSize(unit, workspace)}</dd></div><div><dt>Condition</dt><dd><select value={unit.condition} disabled={saving} onChange={(event) => void onUpdate(unit.id, { condition: event.target.value as VenueMachine["condition"] })}><option>NEW</option><option>USED</option></select></dd></div><div><dt>For sale</dt><dd><label className="asset-switch"><input type="checkbox" checked={unit.forSale} disabled={saving} onChange={(event) => void onUpdate(unit.id, { forSale: event.target.checked })} /><i /></label></dd></div><div><dt>Maintenance</dt><dd><select value={unit.maintenanceStatus} disabled={saving} onChange={(event) => void onUpdate(unit.id, { maintenanceStatus: event.target.value as VenueMachine["maintenanceStatus"] })}>{["OK", "NEEDS_REPAIR", "WAITING_PARTS", "UNDER_REPAIR"].map((status) => <option key={status}>{status}</option>)}</select></dd></div></dl><label className="asset-note">Maintenance note<textarea value={note} onChange={(event) => setNote(event.target.value)} onBlur={saveNote} placeholder="Add a repair or condition note…" /></label><div className="asset-parts"><b>Missing parts</b>{unit.missingParts.map((item) => <span key={item.id}>{item.name} × {item.quantity}<button disabled={saving} onClick={() => void onUpdate(unit.id, { missingParts: unit.missingParts.filter((partItem) => partItem.id !== item.id) })}><X size={12} /></button></span>)}<div><input value={part} onChange={(event) => setPart(event.target.value)} placeholder="Add missing part" onKeyDown={(event) => { if (event.key === "Enter") addPart(); }} /><button onClick={addPart}>Add</button></div></div><div className="asset-drawer-actions"><button onClick={onDuplicate} disabled={saving}><CopySimple size={15} /> Copy</button><button className="danger" onClick={onDelete} disabled={saving}>Delete</button></div></aside>; }
function ShipmentList({ workspace, shipmentUnitIds: _shipmentUnitIds, onRefresh, onAllocate, setError }: { workspace: MachineAssetWorkspace; shipmentUnitIds: Set<string>; onRefresh: () => Promise<void>; onAllocate: (id: string) => void; setError: (message: string) => void }) { const [busy, setBusy] = useState<string | null>(null); return <div className="shipment-list">{workspace.shipments.map((shipment) => { const units = workspace.shipmentItems.filter((item) => item.shipmentId === shipment.id).map((item) => workspace.units.find((unit) => unit.id === item.venueMachineId)).filter(Boolean) as VenueMachine[]; const grouped = units.reduce<Record<string, number>>((acc, unit) => { const label = machineName(unit, workspace); acc[label] = (acc[label] ?? 0) + 1; return acc; }, {}); const doStatus = async (status: ShipmentStatus) => { setBusy(shipment.id); try { await patchShipment(shipment.id, { status }); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update shipment."); } finally { setBusy(null); } }; return <article className="shipment-card" key={shipment.id}><header><div><p className="eyebrow">{shipment.shipmentRef || "Unreferenced shipment"}</p><h3>{Object.entries(grouped).map(([name, quantity]) => `${quantity} × ${name}`).join(" · ") || "No machines"}</h3><small>{units.length} physical units · ETA {shipment.expectedArrivalDate || "not set"}</small></div><span className="shipment-status">{statusLabel(shipment.status)}</span></header>{shipment.notes ? <p>{shipment.notes}</p> : null}<footer><select value={shipment.status} disabled={busy === shipment.id} onChange={(event) => void doStatus(event.target.value as ShipmentStatus)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button disabled={shipment.status === "CLOSED" || !units.length} onClick={() => onAllocate(shipment.id)}><Package size={15} /> Receive & allocate</button></footer></article>; })}{!workspace.shipments.length ? <div className="asset-empty"><ShippingContainer size={26} /> No shipments yet. Create one when stock is ordered.</div> : null}</div>; }
function ShipmentDialog({ models, units, onClose, onSaved, setError }: { models: MachineAssetWorkspace["models"]; units: VenueMachine[]; onClose: () => void; onSaved: () => Promise<void>; setError: (message: string) => void }) { const [shipmentRef, setShipmentRef] = useState(""); const [eta, setEta] = useState(""); const [status, setStatus] = useState<ShipmentStatus>("ORDERED"); const [notes, setNotes] = useState(""); const [machineId, setMachineId] = useState(models[0]?.id ?? ""); const [quantity, setQuantity] = useState(1); const [lines, setLines] = useState<Array<{ machineId: string; quantity: number }>>([]); const [busy, setBusy] = useState(false); const addLine = () => { if (!machineId || quantity < 1) return; setLines((value) => [...value, { machineId, quantity }]); };
  const save = async () => { setBusy(true); try { await createShipment({ shipmentRef, expectedArrivalDate: eta, status, notes, lines }, units); await onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create shipment."); } finally { setBusy(false); } };
  return <div className="asset-modal-backdrop"><section className="asset-modal"><button className="asset-close" onClick={onClose}><X size={18} /></button><h2>New shipment</h2><p>Create the physical units now. They remain unassigned until received and allocated.</p><div className="asset-form-grid"><label>Shipment ref<input value={shipmentRef} onChange={(event) => setShipmentRef(event.target.value)} placeholder="PO or container reference" /></label><label>Expected arrival<input type="date" value={eta} onChange={(event) => setEta(event.target.value)} /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as ShipmentStatus)}>{statuses.map((item) => <option key={item}>{statusLabel(item)}</option>)}</select></label></div><label className="asset-note">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="shipment-line-maker"><select value={machineId} onChange={(event) => setMachineId(event.target.value)}>{models.map((model) => <option key={model.id} value={model.id}>{model.name} · {model.category}</option>)}</select><input type="number" min="1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /><button onClick={addLine}>Add line</button></div><div className="shipment-lines">{lines.map((line, index) => <span key={`${line.machineId}-${index}`}>{line.quantity} × {models.find((model) => model.id === line.machineId)?.name}<button onClick={() => setLines((value) => value.filter((_, itemIndex) => itemIndex !== index))}><X size={12} /></button></span>)}</div><footer><button onClick={onClose}>Cancel</button><button className="asset-primary" disabled={!lines.length || busy} onClick={() => void save()}>{busy ? "Creating…" : "Create shipment"}</button></footer></section></div>; }
function AllocateDialog({ shipment, workspace, onClose, onSaved, setError }: { shipment: NonNullable<MachineAssetWorkspace["shipments"][number]>; workspace: MachineAssetWorkspace; onClose: () => void; onSaved: () => Promise<void>; setError: (message: string) => void }) { const units = workspace.shipmentItems.filter((item) => item.shipmentId === shipment.id).map((item) => workspace.units.find((unit) => unit.id === item.venueMachineId)).filter(Boolean) as VenueMachine[]; const [selected, setSelected] = useState<string[]>(units.map((unit) => unit.id)); const [venueId, setVenueId] = useState(workspace.venues[0]?.id ?? ""); const [busy, setBusy] = useState(false); const save = async () => { if (!selected.length || !venueId) return; setBusy(true); try { await allocateShipmentMachines(selected, venueId); if (shipment.status !== "ARRIVED" && shipment.status !== "CLOSED") await patchShipment(shipment.id, { status: "ARRIVED" }); await onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not allocate shipment machines."); } finally { setBusy(false); } };
  return <div className="asset-modal-backdrop"><section className="asset-modal"><button className="asset-close" onClick={onClose}><X size={18} /></button><h2>Receive & allocate</h2><p>Choose the machines received and their destination. They will appear as Unplaced at that venue.</p><label>Destination venue<select value={venueId} onChange={(event) => setVenueId(event.target.value)}>{workspace.venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</select></label><div className="allocate-list">{units.map((unit) => <label key={unit.id}><input type="checkbox" checked={selected.includes(unit.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, unit.id] : items.filter((id) => id !== unit.id))} /><span><b>{unit.machineCode}</b>{machineName(unit, workspace)}</span></label>)}</div><footer><button onClick={onClose}>Cancel</button><button className="asset-primary" disabled={!selected.length || !venueId || busy} onClick={() => void save()}><CheckCircle size={15} /> {busy ? "Receiving…" : "Receive selected"}</button></footer></section></div>; }
