import { Circle, Group, Image as KonvaImage, Layer, Line, Rect, Stage, Text } from "react-konva";
import type { KonvaEventObject } from "konva/lib/Node";
import { UploadSimple } from "@phosphor-icons/react";
import useImage from "use-image";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { clampFootprintCenterPx, mmToPx, pxToMm, screenToFloorLocal } from "../../lib/floor-plan/coordinates";
import { distanceBetween, isValidScaleInput, calculateScaleMmPerPx, metresToMillimetres, millimetresToMetres, formatMetres, niceMetres, KOKO_RHODES_SCALE_MM_PER_PX } from "../../lib/floor-plan/scale";
import { cacheFloorPlan, cacheLayoutMachines, loadPersistedFloorPlan, loadPersistedLayoutMachines } from "../../lib/floor-plan/persistence";
import { createEmptyFloorPlan, createEmptyLayout, useFloorPlanStore } from "../../store/floorPlanStore";
import { MachineObject } from "./MachineObject";
import { SelectionInteractionOverlay } from "./SelectionInteractionOverlay";
import { getEffectiveMachineDimensions } from "../../lib/floor-plan/machineDimensions";
import { footprintScreenBounds, panToRevealBounds, REVEAL_FOOTPRINT_EVENT, revealMachineVisualCard } from "../../lib/floor-plan/navigation";
import { notifyConnectionLayout } from "../../lib/floor-plan/connection";
import { exportFloorPlanPng } from "../../lib/floor-plan/export";
import { getSupabaseClient } from "../../lib/supabase/client";

const padding = 42;
export function FloorPlanCanvas() {
  const hostRef = useRef<HTMLDivElement>(null); const dragStart = useRef<{ x: number; y: number } | null>(null); const fittedSourceRef = useRef<string | null>(null); const [transientRotation, setTransientRotation] = useState<number | null>(null); const [deleteConfirm, setDeleteConfirm] = useState<string[] | null>(null);
  const [viewport, setViewport] = useState({ width: 820, height: 520 }); const [distanceInput, setDistanceInput] = useState("5"); const [dialogOpen, setDialogOpen] = useState(false); const [contextMenu, setContextMenu] = useState<{ x: number; y: number; id: string } | null>(null); const [newBufferOpen, setNewBufferOpen] = useState(false); const [newBufferName, setNewBufferName] = useState(""); const [newBufferDestination, setNewBufferDestination] = useState(""); const [newBufferMachineIds, setNewBufferMachineIds] = useState<string[]>([]);
  const { venue, projects, layout, floorPlan, zoom, pan, activeTool, backgroundEditing, calibrationPoints, feedback, setFloorPlan, setLayout, setZoom, setPan, setActiveTool, setCalibrationPoints, setFeedback, machines, venueMachines, layoutMachines, transferBuffers, setLayoutMachines, saveFloorPlanUpload, patchFloorPlan, placeMachine, placeBufferMachine, moveLayoutMachine, moveVenueMachinesToBuffer, createTransferBufferAndMove, setSelectedMachineId, selectedMachineId, selectedVenueMachineIds, hoveredVenueMachineId, draggingVenueMachineId, setHoveredVenueMachineId, setDraggingVenueMachineId, hasHydrated } = useFloorPlanStore();
  useEffect(() => { const close = () => setContextMenu(null); const key = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; window.addEventListener("click", close); window.addEventListener("keydown", key); return () => { window.removeEventListener("click", close); window.removeEventListener("keydown", key); }; }, []);
  const floorPlanSource = floorPlan.imageDataUrl ?? floorPlan.imageUrl ?? "";
  const floorOffset = { x: floorPlan.backgroundOffsetX ?? 0, y: floorPlan.backgroundOffsetY ?? 0 };
  const [image] = useImage(floorPlanSource);
  const fitPlan = useCallback(() => {
    if (!floorPlan.imageWidthPx || !floorPlan.imageHeightPx) return;
    const nextZoom = Math.min((viewport.width - padding * 2) / floorPlan.imageWidthPx, (viewport.height - padding * 2) / floorPlan.imageHeightPx);
    setZoom(Math.max(0.25, Math.min(4, nextZoom))); setPan({ x: (viewport.width - floorPlan.imageWidthPx * nextZoom) / 2 - floorOffset.x * nextZoom, y: (viewport.height - floorPlan.imageHeightPx * nextZoom) / 2 - floorOffset.y * nextZoom });
  }, [floorOffset.x, floorOffset.y, floorPlan.imageHeightPx, floorPlan.imageWidthPx, setPan, setZoom, viewport.height, viewport.width]);

  useEffect(() => { const observer = new ResizeObserver(([entry]) => { setViewport({ width: Math.floor(entry.contentRect.width), height: Math.floor(entry.contentRect.height) }); notifyConnectionLayout(); }); if (hostRef.current) observer.observe(hostRef.current); return () => observer.disconnect(); }, []);
  useEffect(() => { const handler = () => fitPlan(); window.addEventListener("floorplan:fit", handler); return () => window.removeEventListener("floorplan:fit", handler); }, [fitPlan]);
  useEffect(() => { const handler = (event: Event) => { const nextZoom = Number((event as CustomEvent<number>).detail); if (!Number.isFinite(nextZoom) || !floorPlan.imageWidthPx || !floorPlan.imageHeightPx) return; const clamped = Math.max(0.25, Math.min(4, nextZoom)); const mapCenter = { x: floorPlan.imageWidthPx / 2, y: floorPlan.imageHeightPx / 2 }; setPan({ x: pan.x + (floorOffset.x + mapCenter.x) * (zoom - clamped), y: pan.y + (floorOffset.y + mapCenter.y) * (zoom - clamped) }); setZoom(clamped); }; window.addEventListener("floorplan:zoom-centered", handler); return () => window.removeEventListener("floorplan:zoom-centered", handler); }, [floorOffset.x, floorOffset.y, floorPlan.imageHeightPx, floorPlan.imageWidthPx, pan, setPan, setZoom, zoom]);
  useEffect(() => { if (!image || !floorPlanSource || fittedSourceRef.current === floorPlanSource) return; fittedSourceRef.current = floorPlanSource; fitPlan(); }, [fitPlan, floorPlanSource, image]);
  /**
   * Route hydration is cloud-first and read-only. A cloud-confirmed empty
   * record is intentionally empty; we never substitute a bundled fixture.
   */
  useEffect(() => { if (!hasHydrated) return; let cancelled = false; void (async () => {
    try {
      const [planResult, layoutResult] = await Promise.all([loadPersistedFloorPlan(venue.id), loadPersistedLayoutMachines(venue.id)]);
      if (cancelled) return;
      const origin = planResult.source === "cloud" && layoutResult.source === "cloud" ? "CLOUD_HYDRATION" : "CACHE_RESTORE";
      const plan = planResult.value ?? createEmptyFloorPlan(venue.id);
      const layoutState = layoutResult.value;
      const resolvedLayout = layoutState.layout ?? createEmptyLayout(venue.id, plan.id);
      setFloorPlan(plan, origin);
      setLayout(resolvedLayout, origin);
      setLayoutMachines(layoutState.machines, origin);
      // Cloud reads refresh cache only. They cannot schedule a cloud write.
      if (planResult.source === "cloud") await cacheFloorPlan(plan);
      if (layoutResult.source === "cloud") await cacheLayoutMachines(venue.id, layoutState.machines, resolvedLayout);
      if (origin === "CACHE_RESTORE") setFeedback("Cloud layout is unavailable. Showing cached data only.");
    } catch (error) {
      console.error("[cloud-hydration] floor plan load failed", error);
      if (!cancelled) setFeedback("Floor plan could not be loaded from cloud.");
    }
  })(); return () => { cancelled = true; }; }, [hasHydrated, setFeedback, setFloorPlan, setLayout, setLayoutMachines, venue.id]);
  useEffect(() => {
    const client = getSupabaseClient(); if (!client || !hasHydrated) return;
    let cancelled = false;
    let refreshVersion = 0;
    const refreshFromCloud = async () => {
      const version = ++refreshVersion;
      try {
        const [planResult, layoutResult] = await Promise.all([loadPersistedFloorPlan(venue.id), loadPersistedLayoutMachines(venue.id)]);
        // Realtime must never apply a cache fallback, which could reintroduce
        // a deleted record while the cloud is temporarily unavailable.
        if (cancelled || version !== refreshVersion || planResult.source !== "cloud" || layoutResult.source !== "cloud") return;
        const plan = planResult.value ?? createEmptyFloorPlan(venue.id);
        const layoutState = layoutResult.value;
        const resolvedLayout = layoutState.layout ?? createEmptyLayout(venue.id, plan.id);
        setFloorPlan(plan, "REALTIME_REMOTE");
        setLayout(resolvedLayout, "REALTIME_REMOTE");
        setLayoutMachines(layoutState.machines, "REALTIME_REMOTE");
        await Promise.all([cacheFloorPlan(plan), cacheLayoutMachines(venue.id, layoutState.machines, resolvedLayout)]);
      } catch (error) { console.warn("[cloud-realtime] floor plan refresh failed", error); }
    };
    const channel = client.channel(`floor-plan-${venue.id}`)
      .on("postgres_changes", { event: "*", schema: "public", table: "floor_plans", filter: `venue_id=eq.${venue.id}` }, () => { void refreshFromCloud(); })
      .on("postgres_changes", { event: "*", schema: "public", table: "layouts", filter: `venue_id=eq.${venue.id}` }, () => { void refreshFromCloud(); })
      .on("postgres_changes", { event: "*", schema: "public", table: "layout_machines" }, () => { void refreshFromCloud(); })
      .subscribe((status) => { if (status === "SUBSCRIBED") setFeedback(null); else if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") console.warn("[cloud-realtime] disconnected", { venueId: venue.id, status }); });
    return () => { cancelled = true; void client.removeChannel(channel); };
  }, [hasHydrated, setFeedback, setFloorPlan, setLayout, setLayoutMachines, venue.id]);
  useEffect(() => { const exportPlan = () => { if (!image) { setFeedback("Wait for the floor plan image to finish loading."); return; } exportFloorPlanPng({ venueName: venue.name, layoutName: layout.name, floorPlan, image, layoutMachines, venueMachines, machines }).then(() => setFeedback("PNG export downloaded.")).catch((error) => setFeedback(error instanceof Error ? error.message : "Export failed.")); }; window.addEventListener("floorplan:export", exportPlan); return () => window.removeEventListener("floorplan:export", exportPlan); }, [floorPlan, image, layout.name, layoutMachines, machines, setFeedback, venue.name, venueMachines]);
  useEffect(() => { const reveal = (rawEvent: Event) => { const venueMachineId = (rawEvent as CustomEvent<string>).detail; const layoutMachine = layoutMachines.find((item) => item.venueMachineId === venueMachineId); const venueMachine = venueMachines.find((item) => item.id === venueMachineId); const machine = venueMachine && machines.find((item) => item.id === venueMachine.machineId); const scale = floorPlan.scaleMmPerPx; if (!layoutMachine || !venueMachine || !machine || !scale) return; const dimensions = getEffectiveMachineDimensions(machine, venueMachine); const bounds = footprintScreenBounds({ ...layoutMachine, ...dimensions, scaleMmPerPx: scale, zoom, pan, floorOffset }); const nextPan = panToRevealBounds(bounds, viewport, pan); if (nextPan) setPan(nextPan); }; window.addEventListener(REVEAL_FOOTPRINT_EVENT, reveal); return () => window.removeEventListener(REVEAL_FOOTPRINT_EVENT, reveal); }, [floorOffset.x, floorOffset.y, floorPlan.scaleMmPerPx, layoutMachines, machines, pan, setPan, venueMachines, viewport, zoom]);

  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type)) { setFeedback("Use a PNG, JPG, JPEG, or WebP floor plan."); return; }
    const imageDataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }).catch(() => null);
    if (!imageDataUrl) { setFeedback("The floor plan could not be read."); return; }
    const dimensions = await new Promise<{ width: number; height: number }>((resolve, reject) => { const decoded = new window.Image(); decoded.onload = () => resolve({ width: decoded.naturalWidth, height: decoded.naturalHeight }); decoded.onerror = reject; decoded.src = imageDataUrl; }).catch(() => null);
    if (!dimensions) { setFeedback("The floor plan image could not be decoded."); return; }
    const knownRhodesScale = venue.id === "venue_koko_rhodes" && dimensions.width === 2388 && dimensions.height === 1790 ? KOKO_RHODES_SCALE_MM_PER_PX : null;
    const next = { ...floorPlan, imageDataUrl, imageUrl: null, imageWidthPx: dimensions.width, imageHeightPx: dimensions.height, scaleMmPerPx: knownRhodesScale, updatedAt: new Date().toISOString() };
    // Upload is an explicit user command. The store writes exactly this plan;
    // navigating here never uploads or migrates old image data.
    saveFloorPlanUpload(next);
    setFeedback(knownRhodesScale ? "KOKO Rhodes scale applied: the full 2388 px long edge is assumed to be 70 m." : "Floor plan uploaded. Set the scale when ready.");
  };
  const onPointerDown = (event: KonvaEventObject<MouseEvent>) => { const point = event.target.getStage()?.getPointerPosition(); if (!point) return; if (activeTool === "pan") { dragStart.current = point; return; } if (activeTool !== "calibrate" || !floorPlanSource) return; const local = screenToFloorLocal(point, { zoom, pan }, { offset: floorOffset }); if (local.x < 0 || local.y < 0 || local.x > floorPlan.imageWidthPx || local.y > floorPlan.imageHeightPx) { setFeedback("Choose points on the floor plan image."); return; } const next = calibrationPoints.length === 0 ? [local] : [calibrationPoints[0], local]; if (next.length === 2 && distanceBetween(next[0], next[1]) < 1) { setFeedback("Choose two different points."); return; } setCalibrationPoints(next); if (next.length === 2) setDialogOpen(true); };
  const onPointerMove = (event: KonvaEventObject<MouseEvent>) => { if (activeTool !== "pan" || !dragStart.current) return; const point = event.target.getStage()?.getPointerPosition(); if (!point) return; setPan({ x: pan.x + point.x - dragStart.current.x, y: pan.y + point.y - dragStart.current.y }); dragStart.current = point; notifyConnectionLayout(); };
  const dropMachine = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); const bufferItemId = event.dataTransfer.getData("application/x-buffer-machine"); if (bufferItemId) { setFeedback("Add this machine to the venue first, then place it from Venue Machines."); return; } const scale = floorPlan.scaleMmPerPx; if (!scale) { setFeedback("Set the Floor Plan scale before placing machines."); return; } const rect = hostRef.current?.getBoundingClientRect(); if (!rect) return; const local = screenToFloorLocal({ x: event.clientX - rect.left, y: event.clientY - rect.top }, { zoom, pan }, { offset: floorOffset }); const venueMachineId = event.dataTransfer.getData("application/x-venue-machine"); const venueMachine = venueMachines.find((item) => item.id === venueMachineId); const machine = venueMachine && machines.find((item) => item.id === venueMachine.machineId); if (!venueMachineId || !venueMachine || !machine) return; const dimensions = getEffectiveMachineDimensions(machine, venueMachine); const clamped = clampFootprintCenterPx(local, { widthPx: mmToPx(dimensions.widthMm, scale), heightPx: mmToPx(dimensions.depthMm, scale) }, { widthPx: floorPlan.imageWidthPx, heightPx: floorPlan.imageHeightPx }); const xMm = pxToMm(clamped.x, scale); const yMm = pxToMm(clamped.y, scale); placeMachine(venueMachineId, xMm, yMm); revealMachineVisualCard(venueMachineId); };
  const applyScale = () => { if (calibrationPoints.length !== 2) return; const knownDistanceMm = metresToMillimetres(Number(distanceInput)); const pixelDistance = distanceBetween(calibrationPoints[0], calibrationPoints[1]); if (!isValidScaleInput(knownDistanceMm, pixelDistance)) { setFeedback("Enter a positive known distance in metres."); return; } const scaleMmPerPx = calculateScaleMmPerPx(knownDistanceMm, pixelDistance); patchFloorPlan({ scaleMmPerPx }); setDialogOpen(false); setCalibrationPoints([]); setActiveTool("select"); setFeedback(`Map scale calibrated · 1 px = ${formatMetres(millimetresToMetres(scaleMmPerPx))}`); };
  const line = calibrationPoints.length === 2 ? [calibrationPoints[0].x, calibrationPoints[0].y, calibrationPoints[1].x, calibrationPoints[1].y] : [];
  const transferFootprint = (point: { x: number; y: number }, id: string) => { const target = document.elementFromPoint(point.x, point.y)?.closest<HTMLElement>("[data-buffer-id]"); if (!target?.dataset.bufferId) return false; const ids = selectedVenueMachineIds.includes(id) ? selectedVenueMachineIds : [id]; moveVenueMachinesToBuffer(ids, target.dataset.bufferId); return true; };
  const menuIds = contextMenu ? (selectedVenueMachineIds.includes(contextMenu.id) ? selectedVenueMachineIds : [contextMenu.id]) : [];
  return <section className="canvas-shell" ref={hostRef} aria-label="Floor plan workspace" onDragOver={(event) => event.preventDefault()} onDrop={dropMachine}><input id="floor-plan-upload" className="hidden-upload" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} />
    <Stage width={viewport.width} height={viewport.height} onMouseDown={onPointerDown} onMouseMove={onPointerMove} onMouseUp={() => { dragStart.current = null; }} className={activeTool === "pan" ? "stage--panning" : ""}>
      <Layer><Rect width={viewport.width} height={viewport.height} fill="#f5f8fe" /></Layer>
      <Layer><Group x={pan.x + floorOffset.x * zoom} y={pan.y + floorOffset.y * zoom} scaleX={zoom} scaleY={zoom} draggable={backgroundEditing} onDragEnd={(event) => { if (event.target !== event.currentTarget) return; patchFloorPlan({ backgroundOffsetX: (event.target.x() - pan.x) / zoom, backgroundOffsetY: (event.target.y() - pan.y) / zoom }); notifyConnectionLayout(); }}>{image ? <KonvaImage image={image} width={floorPlan.imageWidthPx} height={floorPlan.imageHeightPx} listening={backgroundEditing} /> : null}{floorPlan.scaleMmPerPx ? layoutMachines.map((layoutMachine) => { const venueMachine = venueMachines.find((item) => item.id === layoutMachine.venueMachineId); const machine = venueMachine && machines.find((item) => item.id === venueMachine.machineId); return venueMachine && machine ? <MachineObject key={layoutMachine.id} layoutMachine={layoutMachine} venueMachine={venueMachine} machine={machine} scaleMmPerPx={floorPlan.scaleMmPerPx!} floorPlanWidthPx={floorPlan.imageWidthPx} floorPlanHeightPx={floorPlan.imageHeightPx} pan={pan} zoom={zoom} floorOffset={floorOffset} selected={selectedMachineId === venueMachine.id} hovered={hoveredVenueMachineId === venueMachine.id} dragging={draggingVenueMachineId === venueMachine.id} draggable={activeTool === "select" && !backgroundEditing} onSelect={() => { setSelectedMachineId(venueMachine.id); revealMachineVisualCard(venueMachine.id); }} onContextMenu={(point) => { if (!selectedVenueMachineIds.includes(venueMachine.id)) setSelectedMachineId(venueMachine.id); setContextMenu({ ...point, id: venueMachine.id }); }} onDropToBuffer={(point) => transferFootprint(point, venueMachine.id)} onHover={(value) => setHoveredVenueMachineId(value ? venueMachine.id : null)} onDragStart={() => { setSelectedMachineId(venueMachine.id); setDraggingVenueMachineId(venueMachine.id); setHoveredVenueMachineId(venueMachine.id); }} onDragEnd={() => { setDraggingVenueMachineId(null); setHoveredVenueMachineId(null); }} onMove={(xMm, yMm) => { moveLayoutMachine(layoutMachine.id, xMm, yMm); notifyConnectionLayout(null); }} onLiveMove={(xMm, yMm) => notifyConnectionLayout({ venueMachineId: venueMachine.id, xMm, yMm })} /> : null; }) : null}</Group></Layer>
      <Layer listening={activeTool === "calibrate"}><Group x={pan.x + floorOffset.x * zoom} y={pan.y + floorOffset.y * zoom} scaleX={zoom} scaleY={zoom}>{line.length ? <Line points={line} stroke="#554cf0" strokeWidth={2 / zoom} dash={[8 / zoom, 6 / zoom]} /> : null}{calibrationPoints.map((point, index) => <Group key={`${point.x}-${point.y}`}><Circle x={point.x} y={point.y} radius={7 / zoom} fill="#554cf0" stroke="#fff" strokeWidth={2 / zoom} /><Text x={point.x + 10 / zoom} y={point.y - 18 / zoom} text={index === 0 ? "A" : "B"} fill="#4139d5" fontStyle="bold" fontSize={13 / zoom} /></Group>)}</Group></Layer>
      <Layer listening={activeTool === "select" && !backgroundEditing}>{selectedMachineId ? (() => { const layoutMachine = layoutMachines.find((item) => item.venueMachineId === selectedMachineId); const venueMachine = venueMachines.find((item) => item.id === selectedMachineId); const machine = venueMachine && machines.find((item) => item.id === venueMachine.machineId); return layoutMachine && venueMachine && machine && floorPlan.scaleMmPerPx ? <SelectionInteractionOverlay layoutMachine={layoutMachine} machine={machine} venueMachine={venueMachine} scaleMmPerPx={floorPlan.scaleMmPerPx} floorPlanWidthPx={floorPlan.imageWidthPx} floorPlanHeightPx={floorPlan.imageHeightPx} pan={pan} floorOffset={floorOffset} zoom={zoom} draggable={activeTool === "select" && !backgroundEditing} onPreview={setTransientRotation} /> : null; })() : null}</Layer>
    </Stage>
    {contextMenu ? <button className="footprint-delete-trigger destructive-action" style={{ left: Math.min(contextMenu.x, window.innerWidth - 250), top: Math.min(contextMenu.y + 188, window.innerHeight - 54) }} onClick={() => { setDeleteConfirm(menuIds); setContextMenu(null); }}>Delete {menuIds.length > 1 ? `${menuIds.length} Machines` : "Machine"}</button> : null}
    {deleteConfirm ? <div className="venue-dialog destructive-dialog" role="dialog" aria-label="Confirm machine deletion"><h3>{deleteConfirm.length > 1 ? `Delete ${deleteConfirm.length} machines?` : "Delete Machine?"}</h3><p>This permanently removes {deleteConfirm.length > 1 ? `${deleteConfirm.length} physical machines` : "this physical machine"} from the system. Machine Models will remain in the Catalog.{deleteConfirm.some((id) => layoutMachines.some((item) => item.venueMachineId === id)) ? " Placed machines will also be removed from the Floor Plan." : ""}</p><div><button onClick={() => setDeleteConfirm(null)}>Cancel</button><button className="destructive-action" onClick={() => { useFloorPlanStore.getState().deleteVenueMachines(deleteConfirm); setDeleteConfirm(null); }}>{deleteConfirm.length > 1 ? `Delete ${deleteConfirm.length} Machines` : "Delete Machine"}</button></div></div> : null}
    {!floorPlanSource ? <div className="canvas-empty-state"><div className="upload-orb"><UploadSimple size={23} /></div><h2>Upload a venue Floor Plan</h2><p>1. Upload a PNG, JPG, JPEG or WebP · 2. Set the map scale in metres · 3. Drag machines onto the plan</p><button className="empty-upload" onClick={() => document.getElementById("floor-plan-upload")?.click()}><UploadSimple size={16} /> Upload Floor Plan</button></div> : null}
    {floorPlanSource && activeTool === "calibrate" ? <div className="calibration-hint">{calibrationPoints.length === 0 ? "Click point A on the floor plan." : calibrationPoints.length === 1 ? "Click point B with a known distance from A." : "Enter the known distance to calibrate."}</div> : null}
    {floorPlan.scaleMmPerPx ? <><div className="scale-readout" title={`${floorPlan.scaleMmPerPx.toPrecision(12)} mm / px`}>Map scale · 1 px = {formatMetres(millimetresToMetres(floorPlan.scaleMmPerPx))}</div><MapRuler scaleMmPerPx={floorPlan.scaleMmPerPx} zoom={zoom} /></> : null}{feedback ? <button className="canvas-feedback" onClick={() => setFeedback(null)}>{feedback}</button> : null}
    {contextMenu ? <div className="footprint-context-menu" style={{ left: Math.min(contextMenu.x, window.innerWidth - 250), top: Math.min(contextMenu.y, window.innerHeight - 220) }} onClick={(event) => event.stopPropagation()}><strong>{venueMachines.find((m) => m.id === contextMenu.id)?.machineCode} · {machines.find((m) => m.id === venueMachines.find((v) => v.id === contextMenu.id)?.machineId)?.name}</strong><button onClick={() => { setSelectedMachineId(contextMenu.id); revealMachineVisualCard(contextMenu.id); setContextMenu(null); }}>Locate in Machine List</button><button onClick={() => { setSelectedMachineId(contextMenu.id); setContextMenu(null); }}>Edit Machine Model</button><span>Move {menuIds.length} Machine{menuIds.length === 1 ? "" : "s"} to Transfer Buffer</span>{transferBuffers.map((buffer) => <button key={buffer.id} onClick={() => { moveVenueMachinesToBuffer(menuIds, buffer.id); setContextMenu(null); }}>{buffer.name}</button>)}<button onClick={() => { setNewBufferMachineIds(menuIds); setNewBufferName(""); setNewBufferDestination(""); setNewBufferOpen(true); setContextMenu(null); }}>+ New Transfer Buffer</button><button onClick={() => { const item = layoutMachines.find((entry) => entry.venueMachineId === contextMenu.id); if (item) useFloorPlanStore.getState().removeLayoutMachine(item.id); setContextMenu(null); }}>Remove from Layout</button></div> : null}
    {newBufferOpen ? <div className="venue-dialog" role="dialog" aria-label="Create Transfer Buffer"><h3>Create Transfer Buffer</h3><label>Name<input autoFocus value={newBufferName} onChange={(event) => setNewBufferName(event.target.value)} /></label><label>Destination (optional)<select value={newBufferDestination} onChange={(event) => setNewBufferDestination(event.target.value)}><option value="">No destination</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div><button onClick={() => setNewBufferOpen(false)}>Cancel</button><button className="primary-action" disabled={!newBufferName.trim()} onClick={() => { createTransferBufferAndMove(newBufferName, newBufferDestination || null, newBufferMachineIds); setNewBufferOpen(false); }}>Create &amp; Move</button></div></div> : null}
    {dialogOpen ? <div className="scale-dialog" role="dialog" aria-label="Known distance"><h3>Known map distance</h3><p>Enter the real distance between A and B.</p><label><input autoFocus type="number" min="0.01" step="0.01" value={distanceInput} onChange={(event) => setDistanceInput(event.target.value)} /><span>m</span></label><div><button onClick={() => { setDialogOpen(false); setCalibrationPoints([]); }}>Cancel</button><button className="primary-action" onClick={applyScale}>Apply</button></div></div> : null}
  </section>;
}
function MapRuler({ scaleMmPerPx, zoom }: { scaleMmPerPx: number; zoom: number }) { const targetPx = 130; const metres = niceMetres(millimetresToMetres((targetPx / zoom) * scaleMmPerPx)); const width = (metresToMillimetres(metres) / scaleMmPerPx) * zoom; return <div className="map-ruler"><div style={{ width: `${width}px` }} /><span>0</span><b style={{ left: `${width}px` }}>{formatMetres(metres)}</b></div>; }
