import { ArrowUDownLeft, ArrowUUpLeft, ArrowsOutSimple, CursorClick, Hand, ImageSquare, MagnifyingGlassMinus, MagnifyingGlassPlus, Ruler, SidebarSimple, Trash, UploadSimple } from "@phosphor-icons/react";
import { useFloorPlanStore } from "../../store/floorPlanStore";

export function FloorPlanToolbar() {
  const { zoom, setZoom, activeTool, setActiveTool, backgroundEditing, setBackgroundEditing, undoLayout, redoLayout, historyIndex, layoutHistory, floorPlan, layoutMachines, deleteFloorPlan } = useFloorPlanStore();
  const hasFloorPlan = Boolean(floorPlan.imageDataUrl || floorPlan.imageUrl);
  return <div className="toolbar" aria-label="Canvas tools">
    <button className="tool-button" aria-label="Toggle panels" title="Show or hide side panels" onClick={() => window.dispatchEvent(new Event("floorplan:toggle-panels"))}><SidebarSimple size={16} /></button><span className="tool-divider" />
    <button className={activeTool === "select" ? "tool-button tool-button--active" : "tool-button"} onClick={() => setActiveTool("select")} aria-label="Select" title="Select and move machines" disabled={backgroundEditing}><CursorClick size={16} /></button>
    <button className={activeTool === "pan" ? "tool-button tool-button--active" : "tool-button"} onClick={() => setActiveTool("pan")} aria-label="Pan" title="Pan the floor plan" disabled={backgroundEditing}><Hand size={16} /></button><span className="tool-divider" />
    <button className="tool-button" onClick={() => window.dispatchEvent(new CustomEvent("floorplan:zoom-centered", { detail: Math.max(0.5, zoom - 0.1) }))} aria-label="Zoom out" title="Zoom out around map center" disabled={!hasFloorPlan}><MagnifyingGlassMinus size={16} /></button>
    <button className="tool-button" onClick={() => window.dispatchEvent(new CustomEvent("floorplan:zoom-centered", { detail: Math.min(1.5, zoom + 0.1) }))} aria-label="Zoom in" title="Zoom in around map center" disabled={!hasFloorPlan}><MagnifyingGlassPlus size={16} /></button>
    <button className="zoom-label" onClick={() => window.dispatchEvent(new CustomEvent("floorplan:zoom-centered", { detail: 1 }))} title="Reset zoom to 100% around map center" disabled={!hasFloorPlan}>{Math.round(zoom * 100)}%</button><button className="tool-button" aria-label="Fit to screen" title="Fit floor plan to workspace" disabled={!hasFloorPlan} onClick={() => window.dispatchEvent(new Event("floorplan:fit"))}><ArrowsOutSimple size={16} /></button><span className="tool-divider" />
    <button className="tool-button" aria-label="Undo" title="Undo layout change" disabled={historyIndex === 0} onClick={undoLayout}><ArrowUDownLeft size={16} /></button><button className="tool-button" aria-label="Redo" title="Redo layout change" disabled={historyIndex >= layoutHistory.length - 1} onClick={redoLayout}><ArrowUUpLeft size={16} /></button>
    <button className={backgroundEditing ? "scale-button scale-button--active" : "scale-button"} disabled={!hasFloorPlan} title="Move the floor plan background" onClick={() => setBackgroundEditing(!backgroundEditing)}><ImageSquare size={15} /> {backgroundEditing ? "Done Editing" : "Edit Floor Plan"}</button>
    <button className={activeTool === "calibrate" ? "scale-button scale-button--active" : "scale-button"} disabled={!hasFloorPlan || backgroundEditing} title="Calibrate using a known distance" onClick={() => setActiveTool("calibrate")}><Ruler size={15} /> Set Scale</button>
    <button className="upload-button" title={hasFloorPlan ? "Replace floor plan image" : "Upload floor plan image"} onClick={() => document.getElementById("floor-plan-upload")?.click()}><UploadSimple size={15} /> {hasFloorPlan ? "Replace" : "Upload"}</button><button className="tool-button tool-button--destructive" disabled={!hasFloorPlan} title="Delete floor plan" onClick={() => { const message = layoutMachines.length ? `This Floor Plan contains ${layoutMachines.length} placed machines. The map and placements will be removed; machines remain Unplaced.` : "This removes the Floor Plan and calibration data."; if (window.confirm(`Delete Floor Plan?\n\n${message}`)) deleteFloorPlan(); }}><Trash size={15} /></button>
  </div>;
}
