import { Circle, Group, Text } from "react-konva";
import { useEffect, useRef, useState } from "react";
import type { LayoutMachine } from "../../types/layout";
import type { Machine, VenueMachine } from "../../types/machine";
import { clampFootprintCenterPx, mmToPx, rotatedFootprintSize } from "../../lib/floor-plan/coordinates";
import { useFloorPlanStore } from "../../store/floorPlanStore";
import { getEffectiveMachineDimensions } from "../../lib/floor-plan/machineDimensions";

type Props = { layoutMachine: LayoutMachine; machine: Machine; venueMachine: VenueMachine; scaleMmPerPx: number; floorPlanWidthPx: number; floorPlanHeightPx: number; pan: { x: number; y: number }; floorOffset: { x: number; y: number }; zoom: number; draggable: boolean; onPreview: (rotation: number | null) => void };
const degrees = (radians: number) => radians * 180 / Math.PI;
const delta = (value: number) => ((value + 180) % 360 + 360) % 360 - 180;

export function SelectionInteractionOverlay({ layoutMachine, machine, venueMachine, scaleMmPerPx, floorPlanWidthPx, floorPlanHeightPx, pan, floorOffset, zoom, draggable, onPreview }: Props) {
  const setRotation = useFloorPlanStore((state) => state.setLayoutRotation); const stageRef = useRef<any>(null); const start = useRef<{ angle: number; rotation: number } | null>(null); const [rotating, setRotating] = useState(false);
  const dimensions = getEffectiveMachineDimensions(machine, venueMachine); const preview = (value: number | null) => { onPreview(value); if (value !== null) useFloorPlanStore.getState().previewLayoutRotation(layoutMachine.id, value); };
  const width = mmToPx(dimensions.widthMm, scaleMmPerPx); const depth = mmToPx(dimensions.depthMm, scaleMmPerPx); const rotation = layoutMachine.rotation; const footprint = rotatedFootprintSize(width, depth, rotation); const centerX = mmToPx(layoutMachine.xMm, scaleMmPerPx); const centerY = mmToPx(layoutMachine.yMm, scaleMmPerPx); const angle = rotation * Math.PI / 180; const distance = Math.abs(width * Math.sin(angle)) / 2 + Math.abs(depth * Math.cos(angle)) / 2 + 26 / zoom; const handleX = Math.sin(angle) * distance; const handleY = -Math.cos(angle) * distance;
  useEffect(() => { if (!rotating) return; const stage = stageRef.current; const update = (event: PointerEvent, commit: boolean) => { stage?.setPointersPositions(event); const point = stage?.getPointerPosition(); if (!point || !start.current) return; const localX = (point.x - pan.x) / zoom - floorOffset.x - centerX; const localY = (point.y - pan.y) / zoom - floorOffset.y - centerY; let next = start.current.rotation + delta(degrees(Math.atan2(localY, localX)) - start.current.angle); if (event.shiftKey) next = Math.round(next / 15) * 15; preview(next); if (commit) { setRotation(layoutMachine.id, next); preview(null); start.current = null; setRotating(false); } }; const move = (event: PointerEvent) => update(event, false); const up = (event: PointerEvent) => update(event, true); window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); window.addEventListener("pointercancel", up, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); window.removeEventListener("pointercancel", up); }; }, [centerX, centerY, floorOffset.x, floorOffset.y, layoutMachine.id, onPreview, pan.x, pan.y, rotating, scaleMmPerPx, setRotation, zoom]);
  if (!draggable) return null;
  return <Group ref={stageRef} x={pan.x + (floorOffset.x + centerX) * zoom} y={pan.y + (floorOffset.y + centerY) * zoom} scaleX={zoom} scaleY={zoom} listening><Group x={handleX} y={handleY} onMouseDown={(event) => { event.cancelBubble = true; event.evt?.preventDefault?.(); const stage = event.target.getStage(); stageRef.current = stage; const point = stage?.getPointerPosition(); if (!point) return; const localX = (point.x - pan.x) / zoom - floorOffset.x - centerX; const localY = (point.y - pan.y) / zoom - floorOffset.y - centerY; start.current = { angle: degrees(Math.atan2(localY, localX)), rotation }; setRotating(true); onPreview(rotation); }}><Circle radius={11 / zoom} fill="#5149ed" stroke="#fff" strokeWidth={1.5 / zoom} /><Text x={-8 / zoom} y={-8 / zoom} width={16 / zoom} height={16 / zoom} text="↻" align="center" verticalAlign="middle" fontSize={14 / zoom} fontStyle="bold" fill="#fff" listening={false} /></Group></Group>;
}
