import { create } from "zustand";
import { machines, venueMachines as seedVenueMachines } from "../data/machines";
import type { FloorPlan, Venue } from "../types/floorPlan";
import type { Layout, LayoutMachine } from "../types/layout";
import type { Machine, TransferBuffer, TransferBufferItem, VenueMachine } from "../types/machine";

export type EditorTool = "select" | "pan" | "calibrate";
const now = () => new Date().toISOString();
const emptyFloorPlan = (venueId: string): FloorPlan => ({ id: `floor_plan_${venueId}`, venueId, imageUrl: null, imageDataUrl: null, imageWidthPx: 0, imageHeightPx: 0, scaleMmPerPx: null, createdAt: now(), updatedAt: now() });
const defaultFloorPlan = (venueId: string): FloorPlan => venueId === "venue_rhodes_warehouse"
  ? { id: `floor_plan_${venueId}`, venueId, imageUrl: "/floor-plans/rhodes-warehouse-zoning-plan.png", imageDataUrl: null, imageWidthPx: 1137, imageHeightPx: 1075, scaleMmPerPx: null, createdAt: now(), updatedAt: now() }
  : venueId === "venue_qa_dense"
    ? { id: `floor_plan_${venueId}`, venueId, imageUrl: "/floor-plans/qa-dense-grid.svg", imageDataUrl: null, imageWidthPx: 1600, imageHeightPx: 1300, scaleMmPerPx: 10, createdAt: now(), updatedAt: now() }
  : emptyFloorPlan(venueId);
export const defaultLayoutMachines = (venueId: string, layoutId: string): LayoutMachine[] => venueId === "venue_qa_dense" ? Array.from({ length: 50 }, (_, index) => ({ id: `layout_machine_QA${String(index + 1).padStart(2, "0")}`, layoutId, venueMachineId: `venue_machine_QA${String(index + 1).padStart(2, "0")}`, xMm: 1400 + (index % 10) * 1450, yMm: 1400 + Math.floor(index / 10) * 2200, rotation: (index % 4) * 90 as LayoutMachine["rotation"] })) : [];

interface FloorPlanState {
  projects: Venue[]; venue: Venue; floorPlan: FloorPlan; layout: Layout; machines: Machine[]; venueMachines: VenueMachine[];
  layoutMachines: LayoutMachine[]; selectedMachineId: string | null; hoveredVenueMachineId: string | null; draggingVenueMachineId: string | null; zoom: number; pan: { x: number; y: number }; activeTool: EditorTool;
  fullStoreView: boolean; backgroundEditing: boolean; calibrationPoints: { x: number; y: number }[]; feedback: string | null; persistenceStatus: "saving" | "saved" | "failed"; lastSavedAt: string | null; transferBuffers: TransferBuffer[]; transferBufferItems: TransferBufferItem[];
  hasHydrated: boolean;
  layoutHistory: LayoutMachine[][]; historyIndex: number;
  selectedVenueMachineIds: string[]; activeBufferId: string | null; selectedBufferItemIds: string[];
  setSelectedMachineId: (id: string | null) => void; setHoveredVenueMachineId: (id: string | null) => void; setDraggingVenueMachineId: (id: string | null) => void; setZoom: (zoom: number) => void; setPan: (pan: { x: number; y: number }) => void;
  setActiveTool: (tool: EditorTool) => void; setFullStoreView: (value: boolean) => void; setBackgroundEditing: (value: boolean) => void; setVenue: (venue: Venue) => void; addVenue: (name: string) => Venue; renameVenue: (id: string, name: string) => void; deleteVenue: (id: string) => boolean; addVenueMachine: (machineId: string, machineCode?: string) => void;
  setFloorPlan: (floorPlan: FloorPlan) => void; deleteFloorPlan: () => void; setCalibrationPoints: (points: { x: number; y: number }[]) => void; setFeedback: (message: string | null) => void; setPersistenceStatus: (status: "saving" | "saved" | "failed") => void;
  setHasHydrated: (value: boolean) => void;
  setVenueMachines: (items: VenueMachine[]) => void; setLayoutMachines: (items: LayoutMachine[]) => void; deleteVenueMachines: (ids: string[]) => void; deleteVenueCascade: (venueId: string, options: { deleteUnusedCatalogModels: boolean }) => boolean; createCatalogMachine: (input: Omit<Machine, "id" | "createdAt" | "updatedAt">, addToVenue: boolean, machineCode?: string) => void; updateCatalogMachine: (id: string, input: Partial<Machine>) => void;
  placeMachine: (venueMachineId: string, xMm: number, yMm: number) => void; placeBufferMachine: (bufferItemId: string, xMm: number, yMm: number) => void; moveLayoutMachine: (id: string, xMm: number, yMm: number) => void; rotateLayoutMachine: (id: string) => void; previewLayoutRotation: (id: string, rotation: number) => void; setLayoutRotation: (id: string, rotation: number) => void; removeLayoutMachine: (id: string) => void; undoLayout: () => void; redoLayout: () => void;
  updateDimensions: (id: string, width: number, depth: number) => void; updateMachineCode: (id: string, code: string) => void; updateMachineCategory: (id: string, category: string) => void; resetDimensions: (id: string) => void; setCustomDimensions: (id: string, enabled: boolean) => void;
  addTransferBuffer: (name: string) => void;
  createTransferBufferAndMove: (name: string, destinationVenueId: string | null, venueMachineIds: string[]) => void;
  renameTransferBuffer: (id: string, name: string) => void; deleteTransferBuffer: (id: string) => void; setActiveBufferId: (id: string | null) => void;
  toggleVenueMachineSelection: (id: string) => void; moveSelectedToBuffer: (bufferId: string) => void; moveVenueMachinesToBuffer: (venueMachineIds: string[], bufferId: string) => void; toggleBufferItemSelection: (id: string) => void; addSelectedBufferToVenue: () => void; moveBufferItemsToVenue: (itemIds: string[], venueId: string) => void; returnSelectedToSource: () => void; hydrateGlobal: (value: { machines: Machine[]; venueMachines: VenueMachine[]; buffers: TransferBuffer[]; items: TransferBufferItem[]; projects?: Venue[] }) => void;
}

const projects: Venue[] = [];
const emptyVenue: Venue = { id: "venue_new", name: "New venue" };
export const useFloorPlanStore = create<FloorPlanState>((set) => ({
  projects, venue: emptyVenue, floorPlan: emptyFloorPlan(emptyVenue.id),
  layout: { id: "layout_current", venueId: emptyVenue.id, floorPlanId: `floor_plan_${emptyVenue.id}`, name: "Current Layout", createdAt: "2026-09-04T00:00:00.000Z", updatedAt: "2026-09-04T00:00:00.000Z" },
  machines, venueMachines: seedVenueMachines, layoutMachines: [], selectedMachineId: null, hoveredVenueMachineId: null, draggingVenueMachineId: null, zoom: 1, pan: { x: 0, y: 0 }, activeTool: "select", fullStoreView: false, backgroundEditing: false, calibrationPoints: [], feedback: null, persistenceStatus: "saved", lastSavedAt: null, hasHydrated: false, layoutHistory: [[]], historyIndex: 0, transferBuffers: [{ id: "buffer_rhodes_parramatta", name: "Rhodes → Parramatta Sep 2026", createdAt: now(), updatedAt: now() }], transferBufferItems: [], selectedVenueMachineIds: [], activeBufferId: null, selectedBufferItemIds: [],
  setSelectedMachineId: (selectedMachineId) => set({ selectedMachineId }), setHoveredVenueMachineId: (hoveredVenueMachineId) => set({ hoveredVenueMachineId }), setDraggingVenueMachineId: (draggingVenueMachineId) => set({ draggingVenueMachineId }), setZoom: (zoom) => set({ zoom }), setPan: (pan) => set({ pan }),
  setActiveTool: (activeTool) => set({ activeTool, calibrationPoints: activeTool === "calibrate" ? [] : useFloorPlanStore.getState().calibrationPoints }), setFullStoreView: (fullStoreView) => set({ fullStoreView }), setBackgroundEditing: (backgroundEditing) => set({ backgroundEditing, activeTool: backgroundEditing ? "select" : useFloorPlanStore.getState().activeTool }),
  setVenue: (venue) => { if (useFloorPlanStore.getState().venue.id === venue.id) return; if (typeof window !== "undefined") localStorage.setItem("floorplan-active-venue", venue.id); const initialLayoutMachines = defaultLayoutMachines(venue.id, `layout_${venue.id}`); set({ venue, floorPlan: defaultFloorPlan(venue.id), layoutMachines: initialLayoutMachines, layoutHistory: [initialLayoutMachines], historyIndex: 0, layout: { id: `layout_${venue.id}`, venueId: venue.id, floorPlanId: `floor_plan_${venue.id}`, name: "Current Layout", createdAt: now(), updatedAt: now() }, selectedMachineId: null, hoveredVenueMachineId: null, draggingVenueMachineId: null, selectedVenueMachineIds: [], zoom: 1, pan: { x: 0, y: 0 }, activeTool: "select", backgroundEditing: false, calibrationPoints: [] }); },
  addVenue: (name) => { const clean = name.trim(); const id = `venue_${Date.now()}_${clean.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "new"}`; const venue = { id, name: clean }; set((state) => ({ projects: [...state.projects, venue] })); useFloorPlanStore.getState().setVenue(venue); return venue; },
  renameVenue: (id, name) => set((state) => { const clean = name.trim(); return clean ? { projects: state.projects.map((venue) => venue.id === id ? { ...venue, name: clean } : venue), venue: state.venue.id === id ? { ...state.venue, name: clean } : state.venue } : {}; }),
  deleteVenue: (id): boolean => useFloorPlanStore.getState().deleteVenueCascade(id, { deleteUnusedCatalogModels: false }),
  addVenueMachine: (machineId, machineCode) => set((state) => {
    if (!state.machines.some((machine) => machine.id === machineId)) return { feedback: "That catalog machine is unavailable." };
    const venueItems = state.venueMachines.filter((item) => item.venueId === state.venue.id);
    const code = machineCode?.trim() || `M${String(venueItems.length + 1).padStart(2, "0")}`;
    if (venueItems.some((item) => item.machineCode.toLocaleLowerCase() === code.toLocaleLowerCase())) return { feedback: `Machine code ${code} already exists in this venue.` };
    const item: VenueMachine = { id: `venue_machine_${Date.now()}`, venueId: state.venue.id, machineId, machineCode: code, useCustomDimensions: false, customWidthMm: null, customDepthMm: null, status: "planned", createdAt: now(), updatedAt: now() };
    return { venueMachines: [...state.venueMachines, item], selectedMachineId: item.id, feedback: `${item.machineCode} added. Drag it onto the calibrated plan.` };
  }),
  setFloorPlan: (floorPlan) => set({ floorPlan }),
  deleteFloorPlan: () => set((state) => { const next: LayoutMachine[] = []; return { floorPlan: emptyFloorPlan(state.venue.id), calibrationPoints: [], layoutMachines: next, layoutHistory: [next], historyIndex: 0, backgroundEditing: false, selectedMachineId: null, feedback: `${state.layoutMachines.length ? `${state.layoutMachines.length} machines are now Unplaced.` : "Floor Plan and calibration removed."}` }; }),
  setCalibrationPoints: (calibrationPoints) => set({ calibrationPoints }), setFeedback: (feedback) => set({ feedback }), setPersistenceStatus: (persistenceStatus) => set({ persistenceStatus, lastSavedAt: persistenceStatus === "saved" ? now() : useFloorPlanStore.getState().lastSavedAt }), setHasHydrated: (hasHydrated) => set({ hasHydrated }),
  setVenueMachines: (venueMachines) => set({ venueMachines }), setLayoutMachines: (layoutMachines) => set({ layoutMachines, layoutHistory: [layoutMachines], historyIndex: 0 }),
  deleteVenueMachines: (ids) => set((state) => { const unique = [...new Set(ids)]; const deleted = new Set(state.venueMachines.filter((item) => unique.includes(item.id)).map((item) => item.id)); if (!deleted.size) return { feedback: "No machines selected." }; const nextLayout = state.layoutMachines.filter((item) => !deleted.has(item.venueMachineId)); return { venueMachines: state.venueMachines.filter((item) => !deleted.has(item.id)), layoutMachines: nextLayout, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), nextLayout], historyIndex: state.historyIndex + 1, transferBufferItems: state.transferBufferItems.filter((item) => !deleted.has(item.venueMachineId)), selectedVenueMachineIds: state.selectedVenueMachineIds.filter((id) => !deleted.has(id)), selectedBufferItemIds: state.selectedBufferItemIds.filter((id) => { const item = state.transferBufferItems.find((entry) => entry.id === id); return !item || !deleted.has(item.venueMachineId); }), selectedMachineId: deleted.has(state.selectedMachineId ?? "") ? null : state.selectedMachineId, feedback: `${deleted.size} machine${deleted.size === 1 ? "" : "s"} deleted.` }; }),
  deleteVenueCascade: (venueId, options) => { const state = useFloorPlanStore.getState(); const owned = state.venueMachines.filter((item) => item.venueId === venueId); const ids = new Set(owned.map((item) => item.id)); const affectedModels = new Set(owned.map((item) => item.machineId)); const remainingProjects = state.projects.filter((project) => project.id !== venueId); const nextVenue = remainingProjects[0] ?? { id: "venue_empty", name: "New venue" }; const remainingMachines = state.machines.filter((machine) => !options.deleteUnusedCatalogModels || !(affectedModels.has(machine.id) && !state.venueMachines.some((item) => !ids.has(item.id) && item.machineId === machine.id))); const nextLayout = state.venue.id === venueId ? [] : state.layoutMachines.filter((item) => !ids.has(item.venueMachineId)); set({ projects: remainingProjects, machines: remainingMachines, venueMachines: state.venueMachines.filter((item) => !ids.has(item.id)), transferBufferItems: state.transferBufferItems.filter((item) => !ids.has(item.venueMachineId)), layoutMachines: nextLayout, layoutHistory: [nextLayout], historyIndex: 0, venue: state.venue.id === venueId ? nextVenue : state.venue, floorPlan: state.venue.id === venueId ? emptyFloorPlan(nextVenue.id) : state.floorPlan, selectedMachineId: null, selectedVenueMachineIds: [], feedback: `${state.projects.find((project) => project.id === venueId)?.name ?? "Venue"} deleted.` }); if (state.venue.id === venueId && remainingProjects[0]) useFloorPlanStore.getState().setVenue(nextVenue); return true; },
  createCatalogMachine: (input, addToVenue, machineCode) => set((state) => { const timestamp = now(); const machine: Machine = { ...input, id: `machine_${Date.now()}`, createdAt: timestamp, updatedAt: timestamp }; if (!addToVenue) return { machines: [...state.machines, machine], feedback: `${machine.name} saved to Machine Catalog.` }; const existing = state.venueMachines.filter((item) => item.venueId === state.venue.id); const code = machineCode?.trim() || `M${String(existing.length + 1).padStart(2, "0")}`; if (existing.some((item) => item.machineCode.toLowerCase() === code.toLowerCase())) return { feedback: `Machine code ${code} already exists in this venue.` }; const unit: VenueMachine = { id: `venue_machine_${Date.now()}`, venueId: state.venue.id, machineId: machine.id, machineCode: code, useCustomDimensions: false, customWidthMm: null, customDepthMm: null, status: "planned", createdAt: timestamp, updatedAt: timestamp }; return { machines: [...state.machines, machine], venueMachines: [...state.venueMachines, unit], selectedMachineId: unit.id, feedback: `${code} added to ${state.venue.name} as Unplaced.` }; }),
  updateCatalogMachine: (id, input) => set((state) => ({ machines: state.machines.map((machine) => machine.id === id ? { ...machine, ...input, updatedAt: now() } : machine) })),
  placeMachine: (venueMachineId, xMm, yMm) => set((state) => { if (state.layoutMachines.some((item) => item.venueMachineId === venueMachineId)) return { feedback: "This machine is already placed." }; const next = [...state.layoutMachines, { id: `layout_machine_${Date.now()}`, layoutId: state.layout.id, venueMachineId, xMm, yMm, rotation: 0 as const }]; return { layoutMachines: next, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), next], historyIndex: state.historyIndex + 1, selectedMachineId: venueMachineId }; }),
  placeBufferMachine: () => set({ feedback: "Add this machine to a venue first, then place it from Venue Machines." }),
  moveLayoutMachine: (id, xMm, yMm) => set((state) => { const next = state.layoutMachines.map((item) => item.id === id ? { ...item, xMm, yMm } : item); return { layoutMachines: next, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), next], historyIndex: state.historyIndex + 1 }; }),
  rotateLayoutMachine: (id) => set((state) => { const next = state.layoutMachines.map((item) => item.id === id ? { ...item, rotation: ((item.rotation + 90) % 360) as LayoutMachine["rotation"] } : item); return { layoutMachines: next, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), next], historyIndex: state.historyIndex + 1 }; }),
  previewLayoutRotation: (id, rotation) => set((state) => ({ layoutMachines: state.layoutMachines.map((item) => item.id === id ? { ...item, rotation: ((rotation % 360) + 360) % 360 } : item) })),
  setLayoutRotation: (id, rotation) => set((state) => { const normalized = ((rotation % 360) + 360) % 360; const next = state.layoutMachines.map((item) => item.id === id ? { ...item, rotation: normalized } : item); return { layoutMachines: next, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), next], historyIndex: state.historyIndex + 1 }; }),
  removeLayoutMachine: (id) => set((state) => { const next = state.layoutMachines.filter((item) => item.id !== id); return { layoutMachines: next, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), next], historyIndex: state.historyIndex + 1, selectedMachineId: state.layoutMachines.find((item) => item.id === id)?.venueMachineId === state.selectedMachineId ? null : state.selectedMachineId }; }),
  undoLayout: () => set((state) => state.historyIndex > 0 ? { historyIndex: state.historyIndex - 1, layoutMachines: state.layoutHistory[state.historyIndex - 1] } : {}),
  redoLayout: () => set((state) => state.historyIndex < state.layoutHistory.length - 1 ? { historyIndex: state.historyIndex + 1, layoutMachines: state.layoutHistory[state.historyIndex + 1] } : {}),
  updateDimensions: (id, width, depth) => set((state) => { const target = state.venueMachines.find((item) => item.id === id); if (!target) return {}; if (target.useCustomDimensions) return { venueMachines: state.venueMachines.map((item) => item.id === id ? { ...item, customWidthMm: width, customDepthMm: depth, updatedAt: now() } : item) }; return { machines: state.machines.map((machine) => machine.id === target.machineId ? { ...machine, widthMm: width, depthMm: depth, updatedAt: now() } : machine) }; }),
  updateMachineCode: (id, code) => set((state) => { const target = state.venueMachines.find((item) => item.id === id); const clean = code.trim(); if (!target || !clean) return { feedback: "Machine code cannot be empty." }; if (state.venueMachines.some((item) => item.id !== id && item.venueId === target.venueId && item.machineCode.toLocaleLowerCase() === clean.toLocaleLowerCase())) return { feedback: `Machine code ${clean} already exists in this venue.` }; return { venueMachines: state.venueMachines.map((item) => item.id === id ? { ...item, machineCode: clean, updatedAt: now() } : item), feedback: `${clean} updated.` }; }),
  updateMachineCategory: (id, category) => set((state) => { const target = state.venueMachines.find((item) => item.id === id); const clean = category.trim(); if (!target || !clean) return {}; const canonical = state.machines.find((machine) => machine.category.trim().toLocaleLowerCase() === clean.toLocaleLowerCase())?.category ?? clean; return { machines: state.machines.map((machine) => machine.id === target.machineId ? { ...machine, category: canonical, updatedAt: now() } : machine) }; }),
  resetDimensions: (id) => set((state) => ({ venueMachines: state.venueMachines.map((item) => item.id === id ? { ...item, useCustomDimensions: false, customWidthMm: null, customDepthMm: null, updatedAt: now() } : item) })),
  setCustomDimensions: (id, enabled) => set((state) => ({ venueMachines: state.venueMachines.map((item) => { if (item.id !== id) return item; const machine = state.machines.find((entry) => entry.id === item.machineId)!; return { ...item, useCustomDimensions: enabled, customWidthMm: enabled ? (item.customWidthMm ?? machine.widthMm) : null, customDepthMm: enabled ? (item.customDepthMm ?? machine.depthMm) : null, updatedAt: now() }; }) })),
  addTransferBuffer: (name) => set((state) => ({ transferBuffers: [...state.transferBuffers, { id: `buffer_${Date.now()}`, name, createdAt: now(), updatedAt: now() }] })),
  createTransferBufferAndMove: (name, destinationVenueId, venueMachineIds) => set((state) => {
    const clean = name.trim(); const ids = [...new Set(venueMachineIds)];
    if (!clean || !ids.length) return { feedback: "Enter a buffer name and select at least one machine." };
    const eligible = state.venueMachines.filter((m) => ids.includes(m.id) && m.venueId !== null);
    if (eligible.length !== ids.length) return { feedback: "Transfer cancelled: selected machines are unavailable." };
    const timestamp = now(); const bufferId = `buffer_${Date.now()}`;
    const nextLayout = state.layoutMachines.filter((item) => !ids.includes(item.venueMachineId));
    return { transferBuffers: [...state.transferBuffers, { id: bufferId, name: clean, destinationVenueId: destinationVenueId || undefined, createdAt: timestamp, updatedAt: timestamp }], transferBufferItems: [...state.transferBufferItems, ...ids.map((venueMachineId, order) => ({ id: `buffer_item_${Date.now()}_${order}`, transferBufferId: bufferId, venueMachineId, sourceVenueId: state.venueMachines.find((m) => m.id === venueMachineId)?.venueId ?? null, addedAt: timestamp, order }))], venueMachines: state.venueMachines.map((m) => ids.includes(m.id) ? { ...m, venueId: null, transferredAt: null, updatedAt: timestamp } : m), layoutMachines: nextLayout, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), nextLayout], historyIndex: state.historyIndex + 1, selectedVenueMachineIds: [], selectedMachineId: null, activeBufferId: bufferId, feedback: `${ids.length} machine${ids.length === 1 ? "" : "s"} moved to ${clean}.` };
  }),
  renameTransferBuffer: (id, name) => set((state) => ({ transferBuffers: state.transferBuffers.map((item) => item.id === id ? { ...item, name, updatedAt: now() } : item) })),
  deleteTransferBuffer: (id) => set((state) => state.transferBufferItems.some((item) => item.transferBufferId === id) ? { feedback: "Move or return machines before deleting this buffer." } : { transferBuffers: state.transferBuffers.filter((item) => item.id !== id), activeBufferId: null }),
  setActiveBufferId: (activeBufferId) => set({ activeBufferId, selectedBufferItemIds: [] }),
  toggleVenueMachineSelection: (id) => set((state) => ({ selectedVenueMachineIds: state.selectedVenueMachineIds.includes(id) ? state.selectedVenueMachineIds.filter((item) => item !== id) : [...state.selectedVenueMachineIds, id] })),
  moveSelectedToBuffer: (bufferId) => useFloorPlanStore.getState().moveVenueMachinesToBuffer(useFloorPlanStore.getState().selectedVenueMachineIds, bufferId),
  moveVenueMachinesToBuffer: (ids, bufferId) => set((state) => { const requestedIds = [...new Set(ids)]; if (!requestedIds.length || !state.transferBuffers.some((buffer) => buffer.id === bufferId)) return { feedback: "Choose a valid Transfer Buffer." }; const already = new Set(state.transferBufferItems.map((item) => item.venueMachineId)); const eligible = state.venueMachines.filter((machine) => requestedIds.includes(machine.id) && machine.venueId !== null && !already.has(machine.id)); if (eligible.length !== requestedIds.length) return { feedback: "Transfer cancelled: one or more machines are already in a Transfer Buffer." }; const transferIds = new Set(eligible.map((machine) => machine.id)); const timestamp = now(); const nextLayout = state.layoutMachines.filter((item) => !transferIds.has(item.venueMachineId)); return { venueMachines: state.venueMachines.map((machine) => transferIds.has(machine.id) ? { ...machine, venueId: null, transferredAt: null, updatedAt: timestamp } : machine), transferBufferItems: [...state.transferBufferItems, ...eligible.map((machine, order) => ({ id: `buffer_item_${Date.now()}_${order}`, transferBufferId: bufferId, venueMachineId: machine.id, sourceVenueId: machine.venueId, addedAt: timestamp, order }))], layoutMachines: nextLayout, layoutHistory: [...state.layoutHistory.slice(0, state.historyIndex + 1), nextLayout], historyIndex: state.historyIndex + 1, selectedVenueMachineIds: [], selectedMachineId: transferIds.has(state.selectedMachineId ?? "") ? null : state.selectedMachineId, feedback: `${eligible.length} machine${eligible.length === 1 ? "" : "s"} moved to Transfer Buffer.` }; }),
  toggleBufferItemSelection: (id) => set((state) => ({ selectedBufferItemIds: state.selectedBufferItemIds.includes(id) ? state.selectedBufferItemIds.filter((item) => item !== id) : [...state.selectedBufferItemIds, id] })),
  addSelectedBufferToVenue: () => useFloorPlanStore.getState().moveBufferItemsToVenue(useFloorPlanStore.getState().selectedBufferItemIds, useFloorPlanStore.getState().venue.id),
  moveBufferItemsToVenue: (itemIds, venueId) => set((state) => { const selected = state.transferBufferItems.filter((item) => itemIds.includes(item.id)); const destination = state.projects.find((project) => project.id === venueId); if (!destination || selected.length !== itemIds.length || new Set(selected.map((item) => item.venueMachineId)).size !== selected.length) return { feedback: "Transfer cancelled: destination or buffer items are unavailable." }; const ids = selected.map((item) => item.venueMachineId); const physical = ids.map((id) => state.venueMachines.find((machine) => machine.id === id)); if (physical.some((machine) => !machine || machine.venueId !== null)) return { feedback: "Transfer cancelled: an item is no longer in the Transfer Buffer." }; const destinationCodes = new Set(state.venueMachines.filter((machine) => machine.venueId === venueId).map((machine) => machine.machineCode.toLocaleLowerCase())); const incomingCodes = new Set<string>(); const conflict = physical.find((machine) => { const code = machine!.machineCode.toLocaleLowerCase(); if (destinationCodes.has(code) || incomingCodes.has(code)) return true; incomingCodes.add(code); return false; }); if (conflict) return { feedback: `${conflict.machineCode} already exists in ${destination.name}. Transfer cancelled.` }; const timestamp = now(); return { venueMachines: state.venueMachines.map((machine) => ids.includes(machine.id) ? { ...machine, venueId, transferredAt: timestamp, updatedAt: timestamp } : machine), transferBufferItems: state.transferBufferItems.filter((item) => !itemIds.includes(item.id)), selectedBufferItemIds: [], feedback: `${ids.length} machine${ids.length === 1 ? "" : "s"} moved to ${destination.name} as Unplaced.` }; }),
  returnSelectedToSource: () => set((state) => { const ids = state.selectedBufferItemIds; const source = new Map(state.transferBufferItems.filter((item) => ids.includes(item.id)).map((item) => [item.venueMachineId, item.sourceVenueId])); return { venueMachines: state.venueMachines.map((machine) => source.has(machine.id) ? { ...machine, venueId: source.get(machine.id)!, updatedAt: now() } : machine), transferBufferItems: state.transferBufferItems.filter((item) => !ids.includes(item.id)), selectedBufferItemIds: [] }; }),
  hydrateGlobal: (value) => set({
    // Keep new bundled catalog data available for existing browser workspaces.
    machines: [...value.machines, ...machines.filter((machine) => !value.machines.some((saved) => saved.id === machine.id))],
    venueMachines: [...value.venueMachines, ...seedVenueMachines.filter((machine) => !value.venueMachines.some((saved) => saved.id === machine.id))],
    projects: [...(value.projects ?? []), ...projects.filter((project) => !(value.projects ?? []).some((saved) => saved.id === project.id))],
    transferBuffers: value.buffers,
    transferBufferItems: value.items,
  }),
}));
